'use client'

import { useState } from 'react'

const PRIORITY_COLORS = {
  high: 'text-red-400 border-red-800/50',
  medium: 'text-amber-400 border-amber-800/50',
  low: 'text-slate-500 border-slate-700/50',
}

const PRIORITY_DOT = {
  high: 'bg-red-400',
  medium: 'bg-amber-400',
  low: 'bg-slate-500',
}

export default function ChecklistDisplay({ sections, tips, timeEstimate, difficulty, emoji }) {
  const [checked, setChecked] = useState({})
  const [copySuccess, setCopySuccess] = useState(false)

  const toggleCheck = (sectionIdx, itemIdx) => {
    const key = `${sectionIdx}-${itemIdx}`
    setChecked(prev => ({ ...prev, [key]: !prev[key] }))
  }

  const totalItems = sections?.reduce((acc, s) => acc + (s.items?.length || 0), 0) || 0
  const checkedCount = Object.values(checked).filter(Boolean).length
  const progress = totalItems > 0 ? Math.round((checkedCount / totalItems) * 100) : 0

  const handleCopyForNotion = () => {
    if (!sections) return

    let text = ''
    sections.forEach((section) => {
      text += `## ${section.heading}\n`
      section.items?.forEach((item) => {
        text += `- [ ] ${item.text} [${item.priority?.toUpperCase() || 'MEDIUM'}]\n`
      })
      text += '\n'
    })

    if (tips?.length) {
      text += '## 💡 Pro Tips\n'
      tips.forEach((tip) => {
        text += `> ${tip}\n`
      })
      text += '\n'
    }

    text += `---\n📊 Difficulty: ${difficulty} | ⏱ Time: ${timeEstimate}\nGenerated by PlannerAI`

    navigator.clipboard.writeText(text).then(() => {
      setCopySuccess(true)
      setTimeout(() => setCopySuccess(false), 2500)
    })
  }

  if (!sections?.length) return null

  return (
    <div id="planner-content">
      {/* Header stats */}
      <div className="flex flex-wrap items-center gap-3 mb-5">
        <div className="text-2xl">{emoji}</div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs text-slate-500">{totalItems} tasks</span>
            <span className="text-slate-700">·</span>
            <span className={`text-xs px-2 py-0.5 rounded-full border ${
              difficulty === 'Beginner' ? 'text-emerald-400 border-emerald-800/50 bg-emerald-900/20' :
              difficulty === 'Intermediate' ? 'text-amber-400 border-amber-800/50 bg-amber-900/20' :
              'text-red-400 border-red-800/50 bg-red-900/20'
            }`}>
              {difficulty}
            </span>
            <span className="text-slate-700">·</span>
            <span className="text-xs text-slate-500">⏱ {timeEstimate}</span>
          </div>
        </div>

        {/* Copy button */}
        <button
          onClick={handleCopyForNotion}
          className={`flex items-center gap-2 px-3 py-2 rounded-xl border text-xs font-medium transition-all duration-200 ${
            copySuccess
              ? 'bg-emerald-500/20 border-emerald-500/40 text-emerald-400'
              : 'bg-slate-800/60 border-slate-700 text-slate-400 hover:border-purple-500/40 hover:text-purple-300'
          }`}
          title="Copy for Notion / Google Sheets / Excel"
        >
          {copySuccess ? (
            <>
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
              Copy for Notion / Sheets
            </>
          )}
        </button>
      </div>

      {/* Progress bar */}
      {checkedCount > 0 && (
        <div className="mb-5">
          <div className="flex justify-between text-xs text-slate-500 mb-1.5">
            <span>Progress</span>
            <span className="text-purple-400 font-medium">{progress}% complete</span>
          </div>
          <div className="h-1.5 bg-slate-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-purple-500 to-violet-400 rounded-full transition-all duration-500"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>
      )}

      {/* Sections */}
      <div className="space-y-5">
        {sections.map((section, sIdx) => (
          <div key={sIdx} className="glass-card rounded-xl p-4 border border-slate-700/50">
            <h3 className="text-sm font-semibold text-purple-300 mb-3 flex items-center gap-2 uppercase tracking-wide">
              <span className="w-1.5 h-1.5 rounded-full bg-purple-400" />
              {section.heading}
            </h3>
            <div className="space-y-2">
              {section.items?.map((item, iIdx) => {
                const key = `${sIdx}-${iIdx}`
                const isChecked = checked[key]
                return (
                  <div
                    key={iIdx}
                    className={`checklist-item flex items-start gap-3 p-2.5 rounded-lg border border-transparent cursor-pointer select-none ${isChecked ? 'checked' : ''}`}
                    onClick={() => toggleCheck(sIdx, iIdx)}
                  >
                    <div className={`w-5 h-5 rounded flex-shrink-0 border-2 flex items-center justify-center mt-0.5 transition-all duration-150 ${
                      isChecked
                        ? 'bg-purple-500 border-purple-500'
                        : 'border-slate-600 bg-transparent'
                    }`}>
                      {isChecked && (
                        <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                        </svg>
                      )}
                    </div>
                    <span className={`text-sm flex-1 leading-snug ${isChecked ? 'line-through text-slate-600' : 'text-slate-300'}`}>
                      {item.text}
                    </span>
                    <span className={`flex-shrink-0 flex items-center gap-1 text-xs mt-0.5 ${PRIORITY_COLORS[item.priority] || PRIORITY_COLORS.medium}`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${PRIORITY_DOT[item.priority] || PRIORITY_DOT.medium}`} />
                    </span>
                  </div>
                )
              })}
            </div>
          </div>
        ))}
      </div>

      {/* Pro Tips */}
      {tips?.length > 0 && (
        <div className="mt-5 p-4 bg-gradient-to-r from-purple-900/20 to-violet-900/20 rounded-xl border border-purple-700/20">
          <h4 className="text-xs font-semibold text-purple-400 uppercase tracking-wider mb-3 flex items-center gap-2">
            <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 20 20">
              <path d="M11 3a1 1 0 10-2 0v1a1 1 0 102 0V3zM15.657 5.757a1 1 0 00-1.414-1.414l-.707.707a1 1 0 001.414 1.414l.707-.707zM18 10a1 1 0 01-1 1h-1a1 1 0 110-2h1a1 1 0 011 1zM5.05 6.464A1 1 0 106.464 5.05l-.707-.707a1 1 0 00-1.414 1.414l.707.707zM5 10a1 1 0 01-1 1H3a1 1 0 110-2h1a1 1 0 011 1zM8 16v-1h4v1a2 2 0 11-4 0zM12 14c.015-.34.208-.646.477-.859a4 4 0 10-4.954 0c.27.213.462.519.476.859h4.001z"/>
            </svg>
            Pro Tips
          </h4>
          <div className="space-y-2">
            {tips.map((tip, i) => (
              <div key={i} className="flex gap-2 text-sm text-slate-400">
                <span className="text-purple-400 flex-shrink-0 font-bold">{i + 1}.</span>
                <span>{tip}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
