'use client'

import { useState } from 'react'
import { addBonusCredits } from '@/lib/credits'

export default function ShareButtons({ title, slug, baseUrl, onCreditsAdded, hasShareBonus }) {
  const [copied, setCopied] = useState(false)
  const [shareSuccess, setShareSuccess] = useState(null)
  const [downloading, setDownloading] = useState(false)

  const pageUrl = `${baseUrl}/planners/${slug}`
  const shareText = `✨ Check out this AI-generated planner: "${title}" — Free printable!`

  const handleShare = (platform) => {
    let url = ''
    if (platform === 'pinterest') {
      const ogImage = `${baseUrl}/api/og-image?title=${encodeURIComponent(title)}`
      url = `https://pinterest.com{encodeURIComponent(pageUrl)}&media=${encodeURIComponent(ogImage)}&description=${encodeURIComponent(shareText)}`
      window.open(url, '_blank', 'width=750,height=550')
    } else if (platform === 'twitter') {
      url = `https://twitter.com{encodeURIComponent(shareText)}&url=${encodeURIComponent(pageUrl)}`
      window.open(url, '_blank', 'width=550,height=420')
    } else if (platform === 'facebook') {
      url = `https://facebook.com{encodeURIComponent(pageUrl)}`
      window.open(url, '_blank', 'width=600,height=400')
    } else if (platform === 'reddit') {
      url = `https://reddit.com{encodeURIComponent(pageUrl)}&title=${encodeURIComponent(shareText)}`
      window.open(url, '_blank', 'width=600,height=600')
    } else if (platform === 'linkedin') {
      url = `https://linkedin.com{encodeURIComponent(pageUrl)}`
      window.open(url, '_blank', 'width=600,height=600')
    }

    setTimeout(() => {
      const newCredits = addBonusCredits()
      setShareSuccess(platform)
      onCreditsAdded?.(newCredits)
      setTimeout(() => setShareSuccess(null), 3000)
    }, 500)
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(pageUrl)
      setCopied(true)
      const newCredits = addBonusCredits()
      onCreditsAdded?.(newCredits)
      setTimeout(() => setCopied(false), 2500)
    } catch {}
  }

  const handleDownloadPDF = async () => {
    if (!hasShareBonus) return
    setDownloading(true)
    
    try {
      const { default: jsPDF } = await import('jspdf')
      const plannerEl = document.getElementById('planner-content')
      
      if (!plannerEl) {
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
        doc.setFillColor(7, 9, 26)
        doc.rect(0, 0, 210, 297, 'F')
        doc.setTextColor(196, 181, 253)
        doc.setFontSize(22)
        doc.setFont('helvetica', 'bold')
        doc.text(title, 20, 30, { maxWidth: 170 })
        doc.setTextColor(148, 163, 184)
        doc.setFontSize(10)
        doc.text(`Generated by YouPlanAI · youplanai.com`, 20, 285)
        doc.save(`${slug}.pdf`)
      } else {
        const { default: html2canvas } = await import('html2canvas')
        const canvas = await html2canvas(plannerEl, {
          backgroundColor: '#07091a',
          scale: 1.5,
          useCORS: true,
        })
        const imgData = canvas.toDataURL('image/png')
        const doc = new jsPDF({ orientation: 'portrait', unit: 'px', format: [canvas.width / 1.5, canvas.height / 1.5] })
        doc.addImage(imgData, 'PNG', 0, 0, canvas.width / 1.5, canvas.height / 1.5)
        doc.save(`${slug}.pdf`)
      }
    } catch (err) {
      console.error('PDF error:', err)
    }
    setDownloading(false)
  }
  const buttons = [
    {
      id: 'pinterest',
      label: shareSuccess === 'pinterest' ? '+3 Credits! ✓' : 'Pinterest',
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 0C5.373 0 0 5.373 0 12c0 5.084 3.163 9.426 7.627 11.174-.105-.949-.2-2.405.042-3.441.218-.937 1.407-5.965 1.407-5.965s-.359-.719-.359-1.782c0-1.668.967-2.914 2.171-2.914 1.023 0 1.518.769 1.518 1.69 0 1.029-.655 2.568-.994 3.995-.283 1.194.599 2.169 1.777 2.169 2.133 0 3.772-2.249 3.772-5.495 0-2.873-2.064-4.882-5.012-4.882-3.414 0-5.418 2.561-5.418 5.207 0 1.031.397 2.138.893 2.738.098.119.112.224.083.345l-.333 1.36c-.053.22-.174.267-.402.161-1.499-.698-2.436-2.889-2.436-4.649 0-3.785 2.75-7.262 7.929-7.262 4.163 0 7.398 2.967 7.398 6.931 0 4.136-2.607 7.464-6.227 7.464-1.216 0-2.359-.632-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0z"/>
        </svg>
      ),
      className: shareSuccess === 'pinterest' ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40' : 'bg-[#E60023]/10 hover:bg-[#E60023]/20 text-red-300 border-red-800/40 hover:border-red-600/60',
      onClick: () => handleShare('pinterest'),
    },
    {
      id: 'twitter',
      label: shareSuccess === 'twitter' ? '+3 Credits! ✓' : 'X',
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
        </svg>
      ),
      className: shareSuccess === 'twitter' ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40' : 'bg-slate-800/60 hover:bg-slate-700/60 text-slate-300 border-slate-700 hover:border-slate-500',
      onClick: () => handleShare('twitter'),
    },
    {
      id: 'reddit',
      label: shareSuccess === 'reddit' ? '+3 Credits! ✓' : 'Reddit',
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M24 11.5c0-1.65-1.35-3-3-3-.96 0-1.86.48-2.42 1.24-1.64-1-3.75-1.64-5.99-1.72l1.23-3.87 3.93.84c.01 1.1.9 2 2 2 1.1 0 2-.9 2-2s-.9-2-2-2c-.84 0-1.56.52-1.86 1.26l-4.38-.94c-.26-.06-.54.1-.62.36l-1.41 4.45c-2.39.04-4.62.69-6.32 1.72-.56-.74-1.44-1.22-2.4-1.22-1.65 0-3 1.35-3 3 0 1.12.63 2.1 1.56 2.6-.04.19-.06.39-.06.59 0 3.31 4.03 6 9 6s9-2.69 9-6c0-.2-.02-.4-.06-.59.93-.5 1.56-1.48 1.56-2.6zM5.5 14c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm12 2c-1.81 1.81-5.18 1.94-5.5 1.94-.31 0-3.69-.12-5.5-1.94-.19-.19-.19-.51 0-.7.19-.19.51-.19.7 0 1.48 1.48 4.3 1.64 4.8 1.64.5 0 3.32-.16 4.8-1.64.19-.19.51-.19.7 0 .19.19.19.51 0 .7zm-.5-2c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2z"/>
        </svg>
      ),
      className: shareSuccess === 'reddit' ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40' : 'bg-[#FF4500]/10 hover:bg-[#FF4500]/20 text-orange-400 border-orange-900/40 hover:border-orange-600/60',
      onClick: () => handleShare('reddit'),
    },
    {
      id: 'facebook',
      label: shareSuccess === 'facebook' ? '+3 Credits! ✓' : 'Facebook',
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"/>
        </svg>
      ),
      className: shareSuccess === 'facebook' ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40' : 'bg-[#1877F2]/10 hover:bg-[#1877F2]/20 text-blue-400 border-blue-900/40 hover:border-blue-600/60',
      onClick: () => handleShare('facebook'),
    },
    {
      id: 'linkedin',
      label: shareSuccess === 'linkedin' ? '+3 Credits! ✓' : 'LinkedIn',
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/>
        </svg>
      ),
      className: shareSuccess === 'linkedin' ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40' : 'bg-[#0A66C2]/10 hover:bg-[#0A66C2]/20 text-sky-400 border-sky-900/40 hover:border-sky-600/60',
      onClick: () => handleShare('linkedin'),
    },
    {
      id: 'copy',
      label: copied ? 'Copied! ✓' : 'Copy Link',
      icon: copied ? (
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
        </svg>
      ) : (
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
        </svg>
      ),
      className: copied ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40' : 'bg-purple-900/30 hover:bg-purple-800/40 text-purple-300 border-purple-700/40 hover:border-purple-500/60',
      onClick: handleCopy,
    },
  ]

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 mb-1">
        <svg className="w-4 h-4 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
        </svg>
        <span className="text-sm text-slate-400 font-medium">Share &amp; Earn Credits</span>
        <span className="text-xs text-purple-400 bg-purple-500/10 px-2 py-0.5 rounded-full">+3 each</span>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
        {buttons.map((btn) => (
          <button
            key={btn.id}
            onClick={btn.onClick}
            className={`flex items-center justify-center gap-2 px-3 py-2 rounded-xl border text-xs font-medium transition-all duration-200 ${btn.className}`}
          >
            {btn.icon}
            {btn.label}
          </button>
        ))}
      </div>

      {/* PDF Download — unlocks after sharing */}
      <div 
        className={`flex items-center gap-3 p-3 rounded-xl border transition-all duration-300 ${
          hasShareBonus
            ? 'border-emerald-500/30 bg-emerald-500/5 cursor-pointer hover:bg-emerald-500/10'
            : 'border-slate-700/50 bg-slate-900/30 opacity-60 cursor-not-allowed'
        }`}
        onClick={hasShareBonus ? handleDownloadPDF : undefined}
        title={hasShareBonus ? 'Download PDF' : 'Share first to unlock PDF download'}
      >
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
          hasShareBonus ? 'bg-emerald-500/20' : 'bg-slate-800'
        }`}>
          {downloading ? (
            <svg className="w-4 h-4 text-emerald-400 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
            </svg>
          ) : (
            <svg className={`w-4 h-4 ${hasShareBonus ? 'text-emerald-400' : 'text-slate-500'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
          )}
        </div>
        <div className="flex-1 min-w-0">
          <div className="text-xs font-semibold text-slate-200">
            {hasShareBonus ? 'Printable PDF Unlocked' : 'Download Printable PDF'}
          </div>
          <div className="text-[10px] text-slate-500 truncate">
            {hasShareBonus ? 'Ready to export to A4/Notion' : 'Share to unlock high-quality PDF export'}
          </div>
        </div>
        {!hasShareBonus && (
          <div className="flex-shrink-0">
            <svg className="w-3.5 h-3.5 text-slate-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
          </div>
        )}
      </div>
    </div>
  )
}
