'use client'

import { useState } from 'react'
import { addBonusCredits } from '@/lib/credits'

export default function ShareButtons({ title, slug, baseUrl, onCreditsAdded, hasShareBonus }) {
  const [copied, setCopied] = useState(false)
  const [shareSuccess, setShareSuccess] = useState(null)
  const [downloading, setDownloading] = useState(false)

  const pageUrl = `${baseUrl}/planners/${slug}`
  const shareText = `✨ Check out this AI-generated planner: "${title}" — Free printable!`

  const handleShare = (platform) => {
    if (platform === 'pinterest') {
      const ogImage = `${baseUrl}/api/og-image?title=${encodeURIComponent(title)}`
      window.open(
        `https://pinterest.com/pin/create/button/?url=${encodeURIComponent(pageUrl)}&media=${encodeURIComponent(ogImage)}&description=${encodeURIComponent(shareText)}`,
        '_blank', 'width=750,height=550'
      )
    } else if (platform === 'twitter') {
      window.open(
        `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(pageUrl)}`,
        '_blank', 'width=550,height=420'
      )
    }

    setTimeout(() => {
      const newCredits = addBonusCredits()
      setShareSuccess(platform)
      onCreditsAdded?.(newCredits)
      setTimeout(() => setShareSuccess(null), 3000)
    }, 500)
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(pageUrl)
      setCopied(true)
      const newCredits = addBonusCredits()
      onCreditsAdded?.(newCredits)
      setTimeout(() => setCopied(false), 2500)
    } catch {}
  }

  const handleDownloadPDF = async () => {
    if (!hasShareBonus) return
    setDownloading(true)
    
    try {
      // Dynamic import to keep bundle lean
      const { default: jsPDF } = await import('jspdf')
      
      // Get the planner content from the page
      const plannerEl = document.getElementById('planner-content')
      if (!plannerEl) {
        // Fallback: generate a basic PDF with text
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
        
        doc.setFillColor(7, 9, 26)
        doc.rect(0, 0, 210, 297, 'F')
        
        doc.setTextColor(196, 181, 253)
        doc.setFontSize(22)
        doc.setFont('helvetica', 'bold')
        doc.text(title, 20, 30, { maxWidth: 170 })
        
        doc.setTextColor(148, 163, 184)
        doc.setFontSize(10)
        doc.text(`Generated by PlannerAI · plannerai.app`, 20, 285)
        
        doc.save(`${slug}.pdf`)
      } else {
        const { default: html2canvas } = await import('html2canvas')
        const canvas = await html2canvas(plannerEl, {
          backgroundColor: '#07091a',
          scale: 1.5,
          useCORS: true,
        })
        
        const imgData = canvas.toDataURL('image/png')
        const doc = new jsPDF({ orientation: 'portrait', unit: 'px', format: [canvas.width / 1.5, canvas.height / 1.5] })
        doc.addImage(imgData, 'PNG', 0, 0, canvas.width / 1.5, canvas.height / 1.5)
        doc.save(`${slug}.pdf`)
      }
    } catch (err) {
      console.error('PDF error:', err)
    }
    
    setDownloading(false)
  }

  const buttons = [
    {
      id: 'pinterest',
      label: shareSuccess === 'pinterest' ? '+3 Credits Added! ✓' : 'Pin on Pinterest',
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 0C5.373 0 0 5.373 0 12c0 5.084 3.163 9.426 7.627 11.174-.105-.949-.2-2.405.042-3.441.218-.937 1.407-5.965 1.407-5.965s-.359-.719-.359-1.782c0-1.668.967-2.914 2.171-2.914 1.023 0 1.518.769 1.518 1.69 0 1.029-.655 2.568-.994 3.995-.283 1.194.599 2.169 1.777 2.169 2.133 0 3.772-2.249 3.772-5.495 0-2.873-2.064-4.882-5.012-4.882-3.414 0-5.418 2.561-5.418 5.207 0 1.031.397 2.138.893 2.738.098.119.112.224.083.345l-.333 1.36c-.053.22-.174.267-.402.161-1.499-.698-2.436-2.889-2.436-4.649 0-3.785 2.75-7.262 7.929-7.262 4.163 0 7.398 2.967 7.398 6.931 0 4.136-2.607 7.464-6.227 7.464-1.216 0-2.359-.632-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0z"/>
        </svg>
      ),
      className: shareSuccess === 'pinterest'
        ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40'
        : 'bg-[#E60023]/10 hover:bg-[#E60023]/20 text-red-300 border-red-800/40 hover:border-red-600/60',
      onClick: () => handleShare('pinterest'),
    },
    {
      id: 'twitter',
      label: shareSuccess === 'twitter' ? '+3 Credits Added! ✓' : 'Share on X',
      icon: (
        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
          <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
        </svg>
      ),
      className: shareSuccess === 'twitter'
        ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40'
        : 'bg-slate-800/60 hover:bg-slate-700/60 text-slate-300 border-slate-700 hover:border-slate-500',
      onClick: () => handleShare('twitter'),
    },
    {
      id: 'copy',
      label: copied ? 'Link Copied! ✓' : 'Copy Link',
      icon: copied ? (
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
        </svg>
      ) : (
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
        </svg>
      ),
      className: copied
        ? 'bg-emerald-700/60 text-emerald-300 border-emerald-600/40'
        : 'bg-purple-900/30 hover:bg-purple-800/40 text-purple-300 border-purple-700/40 hover:border-purple-500/60',
      onClick: handleCopy,
    },
  ]

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 mb-1">
        <svg className="w-4 h-4 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
        </svg>
        <span className="text-sm text-slate-400 font-medium">Share &amp; Earn Credits</span>
        <span className="text-xs text-purple-400 bg-purple-500/10 px-2 py-0.5 rounded-full">+3 each</span>
      </div>

      <div className="flex flex-wrap gap-2">
        {buttons.map((btn) => (
          <button
            key={btn.id}
            onClick={btn.onClick}
            className={`
              flex items-center gap-2 px-4 py-2 rounded-xl border text-sm font-medium
              transition-all duration-200 ${btn.className}
            `}
          >
            {btn.icon}
            {btn.label}
          </button>
        ))}
      </div>

      {/* PDF Download — unlocks after sharing */}
      <div className={`flex items-center gap-3 p-3 rounded-xl border transition-all duration-300 ${
        hasShareBonus
          ? 'border-emerald-500/30 bg-emerald-500/5 cursor-pointer hover:bg-emerald-500/10'
          : 'border-slate-700/50 bg-slate-900/30 opacity-60 cursor-not-allowed'
      }`}
        onClick={hasShareBonus ? handleDownloadPDF : undefined}
        title={hasShareBonus ? 'Download PDF' : 'Share first to unlock PDF download'}
      >
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
          hasShareBonus ? 'bg-emerald-500/20' : 'bg-slate-800'
        }`}>
          {downloading ? (
            <svg className="w-4 h-4 text-emerald-400 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
            </svg>
          ) : (
            <svg className={`w-4 h-4 ${hasShareBonus ? 'text-emerald-400' : 'text-slate-600'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          )}
        </div>
        <div>
          <div className={`text-sm font-medium ${hasShareBonus ? 'text-emerald-300' : 'text-slate-500'}`}>
            {downloading ? 'Generating PDF...' : 'Download Printable PDF'}
          </div>
          <div className="text-xs text-slate-600">
            {hasShareBonus ? 'Click to download your planner as PDF' : 'Share to unlock PDF export'}
          </div>
        </div>
        {!hasShareBonus && (
          <div className="ml-auto">
            <svg className="w-4 h-4 text-slate-600" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clipRule="evenodd"/>
            </svg>
          </div>
        )}
      </div>
    </div>
  )
}
