export default function TermsConditions() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 text-[#c5c6c7]">
        <h1 className="text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-indigo-500 mb-8">Terms and Conditions</h1>
        <p className="text-sm text-gray-500 mb-6">Effective Date: June 5, 2026</p>
        
        <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4 leading-relaxed">By accessing and using YouPlanAI, you agree to comply with and be bound by these Terms and Conditions. If you do not agree, please refrain from using our services.</p>
        </section>

        <section className="mb-8">
            <h2 className="text-2xl font-semibold text-white mb-4">2. Intellectual Property</h2>
            <p className="mb-4 leading-relaxed">The architecture, user interface, and generated output (planners and checklists) of YouPlanAI are protected by copyright laws. Users may use outputs for personal application.</p>
        </section>

        <section className="mb-8">
            <h2 class="text-2xl font-semibold text-white mb-4">3. Limitation of Liability</h2>
            <p class="mb-4 leading-relaxed">The planners generated by our AI are for informational purposes only. YouPlanAI provides no guarantees regarding the practical success of the generated content. Users execute plans at their own risk.</p>
        </section>

        <footer className="border-t border-gray-800 pt-6 mt-12 text-center text-sm">
            <p>If you have any questions, contact us at: <span className="text-purple-400">support@youplanai.com</span></p>
        </footer>
    </div>
  );
}
